version: '3.9'

services:
  payload:
    image: node:22.17.0-alpine
    container_name: destinations-payload
    working_dir: /app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env
    command: >
      sh -c "
        apk add --no-cache libc6-compat &&
        corepack enable pnpm &&
        pnpm install &&
        pnpm dev
      "
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    container_name: destinations-mongo
    ports:
      - '27017:27017'
    volumes:
      - destinations-mongo-data:/data/db
      - C:/Users/marce/Code/Dev/destinations/data/db-dump/dump:/dump
    command: ['mongod', '--bind_ip_all']

volumes:
  destinations-mongo-data:
    name: destinations-mongo-data
